### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer and EOFError:

### ISSUE THREAD

**Issue by jinx-USTC** [jihanyang/AFN#8]
>>training A->W epoch : 20
25it [00:08,  3.00it/s]
>>training A->W epoch : 21
25it [00:08,  2.99it/s]
>>training A->W epoch : 22
25it [00:08,  2.90it/s]
>>training A->W epoch : 23
25it [00:08,  3.00it/s]
>>training A->W epoch : 24
25it [00:08,  2.93it/s]
>>training A->W epoch : 25
25it [00:08,  2.95it/s]
>>training A->W epoch : 26
25it [00:08,  2.96it/s]
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fe467713128>>
Traceback (most recent call last):
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError:
>>training A->W epoch : 27
25it [00:08,  2.99it/s]
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fe46c1bc4e0>>
Traceback (most recent call last):
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/v-lew/anaconda3/envs/PyTorch0.4Python3.6/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError:
>>training A->W epoch : 28
25it [00:08,  2.91it/s]
>>training A->W epoch : 29
25it [00:08,  2.99it/s]

**Comment by jihanyang** [comment]
This error is raised by 'multi processing'  moduler of pytorch, and thus I guess you can try to decrease the `num_workers` of `dataloader`. However, I cannot guarantee this can fix your problem since I cannot reproduce it.
Please refer to similar [issues](https://github.com/pytorch/pytorch/issues/9127) in offical pytorch github for other possible solutions.

**Comment by jinx-USTC** [comment]
Thank you~

**Comment by jinx-USTC** [comment]
Besides, I want to know this problem will whether or not affect the training performance?

**Comment by Bowenwu1** [comment]
Generally speaking, it will not affect the training performance.
